version: "3.8"

services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    restart: always
    env_file:
      - .env         # أو داخليًا يربطه Coolify بقسمة Secrets
    # container_name: postiz     # Best to omit if Coolify يدير الحاويات
    environment:
      # These values will be read from .env or واجهة Coolify قبل deploy
      MAIN_URL: "${MAIN_URL}"
      FRONTEND_URL: "${FRONTEND_URL}"
      NEXT_PUBLIC_BACKEND_URL: "${NEXT_PUBLIC_BACKEND_URL}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_URL: "${REDIS_URL}"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true"
      DISABLE_REGISTRATION: "false"
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"

      # ➕ جميع الإختيارات لسوشيال ميديا (OAuth ID + Secret)
      YOUTUBE_CLIENT_ID: ""
      YOUTUBE_CLIENT_SECRET: ""
      X_API_KEY: ""
      X_API_SECRET: ""
      THREADS_APP_ID: ""
      THREADS_APP_SECRET: ""
      INSTAGRAM_APP_ID: ""
      INSTAGRAM_APP_SECRET: ""
      FACEBOOK_APP_ID: ""
      FACEBOOK_APP_SECRET: ""
      LINKEDIN_CLIENT_ID: ""
      LINKEDIN_CLIENT_SECRET: ""
      REDDIT_CLIENT_ID: ""
      REDDIT_CLIENT_SECRET: ""
      PINTEREST_CLIENT_ID: ""
      PINTEREST_CLIENT_SECRET: ""
      DRIBBBLE_CLIENT_ID: ""
      DRIBBBLE_CLIENT_SECRET: ""
      MASTODON_CLIENT_ID: ""
      MASTODON_CLIENT_SECRET: ""
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""
      TELEGRAM_BOT_NAME: ""
      TELEGRAM_TOKEN: ""

    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    ports:
      - "5000:5000"
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    networks:
      - postiz-network

  postiz-postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postiz-user
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: postiz
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postiz-user -d postiz
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - postiz-network

  postiz-redis:
    image: redis:7.2
    restart: always
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network

volumes:
  postgres-volume:
    external: false
  postiz-redis-data:
    external: false
  postiz-config:
    external: false
  postiz-uploads:
    external: false

networks:
  postiz-network:
    external: false
